<?php /** @var \Aligent\SocialLinks\Block\SocialLinks $block */ ?>

<?php if (count($block->getUsernames()) > 0): ?>
    <div class="aligent-social-links-container">
        <div class="aligent-social-links-inner-container">
            <ul class="aligent-social-links">
                <?php foreach ($block->getUsernames() as $network => $username): ?>
                    <li>
                        <a class="aligent-social__link social__link--<?php echo $network ?>" href="<?php echo $block->getSocialLink($network, $username) ?>">
                            <?php if ($block->displaySocialNetworkName()): ?>
                                <span class="aligent-social__text aligent-social__text--network"><?php echo ucfirst($network) ?></span>
                            <?php endif; ?>
                            <?php if ($block->displaySocialNetworkUsername()): ?>
                                <span class="aligent-social__text aligent-social__text--username"><?php echo $username ?></span>
                            <?php endif; ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
